# overriding conda-forge-pinnings defined in
# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

# conda-forge uses gcc on linux and clang on osx
# we're only supporting clang on both platforms
c_compiler:
    - clang
c_compiler_version:
    - 9
cxx_compiler:
    - clangxx
cxx_compiler_version:
    - 9

# override macos APK min version.
# conda-forge supports from 10.9 but we
# have code that needs 10.13.
# See https://sifive.atlassian.net/wiki/x/0IBBJw
# for details
macos_min_version:             # [osx]
  - 10.13                      # [osx]
MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.13                      # [osx]
