recipe_dir: recipe
skip_render:
  - README.md
  - LICENSE.txt
  - .gitattributes
  - .gitignore
  - LICENSE
  - .github/CONTRIBUTING.md
  - .github/ISSUE_TEMPLATE.md
  - .github/PULL_REQUEST_TEMPLATE.md
  - .circleci/config.yml
  - .github/workflows/main.yml
  - .github/workflows/webservices.yml
provider:
  linux: azure
  osx: azure
  win: None
  linux_ppc64le: None
  linux_aarch64: None
azure:
  force: False
